language: node_js
os: gnu-linux

git:
  depth: 3

branches:
  except:
    - legacy
    - experimental
  only:
    - master
    - stable

before_install:
  - python

install: 
  - yarn install

script:
  - yarn deploy
  - yarn test

before_script:
  - yarnt test

after_script:
  - yarn clean

cache:
  directories:
    - node_modules

jobs:
  include: 
    - stage: test
      script: yarn test
      script: yarn eslint
    - stage: deploy
      script: yarn deploy

deploy:
  provider: heroku
  on
    repo: LeonAngelit/Platzi-store


