language: node_js
os: gnu-linux

git:
  depth: 3

branches:
  except:
    - legacy
    - experimental
  only:
    - master
    - main
    - stable

script:
  - yarn build

before_script:
  - yart test

after_script:
  - yarn clean

cache:
  directories:
    - node_modules
    - ~/.npm

  node_js: 
    - '14'

jobs:
  include: 
    - stage: test
      script: yarn test
      script: yarn eslint
    - stage: deploy
      script: yarn deploy

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  target_branch: gh-pages
  commit_message: "Deploy del proyecto"
  on:
    branch: main



